CREATE TABLE EQUIP(
 idequipamento int IDENTITY (1,1) PRIMARY KEY,
 placa varchar(10) not null,
 matricula varchar(10) not null,
 ano varchar(4) not null,
 fabricante varchar(50) not null,
 id_modelo int not null,
 nu_grupo int not null,
 serieouchassi varchar(100) not null,
 renavam varchar(100) not null,
 crv varchar(100) not null,
 capacidadetanque varchar(500) not null,
 horimetro varchar(10) not null,
 hodometro  varchar(10) not null,
 horimetroa decimal(7,0) not null,
 hodometroa decimal(7,0) not null,
 producaoh decimal(7,0) not null,
 producaok decimal(7,0) not null,
 eixo varchar(10) not null,
 nucontrato varchar(500) not null,
 contrato varchar(100) not null,
 logradouro varchar(80) not null,
 uf varchar(5) not null,
 responsavelpelocontrato varchar(200) not null,
 criticidadeatividade varchar(100) not null,
 implemento varchar(20) not null,
 cor varchar(15) not null,
 potencia varchar(10) not null,
 CMT varchar(10) not null,
 peso_op varchar(9) not null,
 seriemotor varchar(60) not null,
 capacidadedecarga varchar(9) not null,
 inativo varchar(10) not null,
 combustivel varchar(10) not null,
 consumoprevistohh decimal(7,0) not null,
 consumoprevistokm decimal(7,0) not null,
 consumoporhh decimal(7,0) not null,
 consumoporkm decimal(7,0) not null,
 totaldespesa real ,
 mediadespesakm real,
 mediadespesahh real,
 tempoparado time ,
 autonomiahh decimal(7,0) ,
 autonomiakm decimal(7,0) ,
 datacompra date ,
 datavenda date,
 datainiciogarantia date ,
 datafimgarantia date,
 statusgarantia varchar(100),
 tacografo varchar(20),
 dataafericaotacografo date ,
 dataproximaafericao date ,
 statustacografo varchar(20) ,
 observacaotacografo varchar(200) ,
 acompanhamentopreventiva varchar(80) not null,
 observacao varchar(500) ,
 ultimaalteracao varchar(100) not null,
 dataalteracao date not null,
 horaalteracao time not null,
)